include_guard(GLOBAL)
include(FetchContent)

# ── Dependency guards — падаем с понятным сообщением, не cryptic linker error ──
macro(dsp_check_dependency_guards)
    if(DSP_BUILD_SPECTRUM AND NOT DSP_BUILD_CORE)
        message(FATAL_ERROR "[DSP] spectrum требует DSP_BUILD_CORE=ON")
    endif()
    if(DSP_BUILD_STATS AND NOT DSP_BUILD_CORE)
        message(FATAL_ERROR "[DSP] stats требует DSP_BUILD_CORE=ON")
    endif()
    if(DSP_BUILD_LINALG AND NOT DSP_BUILD_CORE)
        message(FATAL_ERROR "[DSP] linalg требует DSP_BUILD_CORE=ON")
    endif()
    if(DSP_BUILD_SIGNAL_GENERATORS)
        if(NOT DSP_BUILD_CORE OR NOT DSP_BUILD_SPECTRUM)
            message(FATAL_ERROR "[DSP] signal_generators требует DSP_BUILD_CORE=ON + DSP_BUILD_SPECTRUM=ON")
        endif()
    endif()
    if(DSP_BUILD_HETERODYNE)
        if(NOT DSP_BUILD_CORE OR NOT DSP_BUILD_SPECTRUM OR NOT DSP_BUILD_SIGNAL_GENERATORS)
            message(FATAL_ERROR "[DSP] heterodyne требует CORE + SPECTRUM + SIGNAL_GENERATORS")
        endif()
    endif()
    if(DSP_BUILD_RADAR)
        if(NOT DSP_BUILD_CORE OR NOT DSP_BUILD_SPECTRUM OR NOT DSP_BUILD_STATS)
            message(FATAL_ERROR "[DSP] radar требует CORE + SPECTRUM + STATS")
        endif()
    endif()
    if(DSP_BUILD_STRATEGIES)
        foreach(_req CORE SPECTRUM STATS SIGNAL_GENERATORS HETERODYNE LINALG RADAR)
            if(NOT DSP_BUILD_${_req})
                message(FATAL_ERROR "[DSP] strategies требует DSP_BUILD_${_req}=ON")
            endif()
        endforeach()
    endif()
endmacro()

# Значения по умолчанию — перекрываются через -D или CMakePresets.json
set(DSP_CORE_TAG              "v0.1.0" CACHE STRING "Tag for DspCore")
set(DSP_SPECTRUM_TAG          "v0.1.0" CACHE STRING "Tag for DspSpectrum")
set(DSP_STATS_TAG             "v0.1.0" CACHE STRING "Tag for DspStats")
set(DSP_SIGNAL_GENERATORS_TAG "v0.1.0" CACHE STRING "Tag for DspSignalGenerators")
set(DSP_HETERODYNE_TAG        "v0.1.0" CACHE STRING "Tag for DspHeterodyne")
set(DSP_LINALG_TAG            "v0.1.0" CACHE STRING "Tag for DspLinalg")
set(DSP_RADAR_TAG             "v0.1.0" CACHE STRING "Tag for DspRadar")
set(DSP_STRATEGIES_TAG        "v0.1.0" CACHE STRING "Tag for DspStrategies")

# FIND_PACKAGE_ARGS: сначала пробует системный пакет, иначе клонирует с GitHub.
# При локальной разработке: FETCHCONTENT_SOURCE_DIR_DSP* → локальная папка.
function(dsp_fetch_package name repo tag_var)
  FetchContent_Declare(${name}
    GIT_REPOSITORY https://github.com/dsp-gpu/${repo}.git
    GIT_TAG        ${${tag_var}}
    GIT_SHALLOW    TRUE
    FIND_PACKAGE_ARGS NAMES ${name} CONFIG
  )
  FetchContent_MakeAvailable(${name})
endfunction()

# Удобные обёртки — читают *_TAG из cache:
function(fetch_dsp_core)
  dsp_fetch_package(DspCore core DSP_CORE_TAG)
endfunction()
function(fetch_dsp_spectrum)
  dsp_fetch_package(DspSpectrum spectrum DSP_SPECTRUM_TAG)
endfunction()
function(fetch_dsp_stats)
  dsp_fetch_package(DspStats stats DSP_STATS_TAG)
endfunction()
function(fetch_dsp_signal_generators)
  dsp_fetch_package(DspSignalGenerators signal_generators DSP_SIGNAL_GENERATORS_TAG)
endfunction()
function(fetch_dsp_heterodyne)
  dsp_fetch_package(DspHeterodyne heterodyne DSP_HETERODYNE_TAG)
endfunction()
function(fetch_dsp_linalg)
  dsp_fetch_package(DspLinalg linalg DSP_LINALG_TAG)
endfunction()
function(fetch_dsp_radar)
  dsp_fetch_package(DspRadar radar DSP_RADAR_TAG)
endfunction()
function(fetch_dsp_strategies)
  dsp_fetch_package(DspStrategies strategies DSP_STRATEGIES_TAG)
endfunction()
